general.kafka-topic=test-topic
spring.kafka.producer.keySerializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.valueSerializer=org.springframework.kafka.support.serializer.JsonSerializer
server.port=33400