# H2 Database Configuration
# Set the URL for our in-memory database named 'midasdb'
spring.datasource.url=jdbc:h2:mem:midasdb
# Default H2 username
spring.datasource.username=sa
# Default H2 password (blank)
spring.datasource.password=
# The H2 driver
spring.datasource.driver-class-name=org.h2.Driver

# H2 Console
# This enables a web-based console to view our database
spring.h2.console.enabled=true
# We'll set the path to the console to /h2-console
spring.h2.console.path=/h2-console

# JPA Configuration
# This tells Hibernate (the JPA provider) to automatically create/update 
# the database tables based on our @Entity classes
spring.jpa.hibernate.ddl-auto=update
# Kafka Topic Configuration
general.kafka-topic=test-topic
# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=midas-core-group
# Specify deserializers for the consumer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer