package com.jpmc.midascore;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;

@Entity
@Table(name = "transactions") // Maps this class to a table named 'transactions'
@Data // Lombok: Generates Getters, toString, equals, and hashCode
@Setter // Lombok: Specifically enables setters, needed for JSON deserialization
@NoArgsConstructor // Lombok: Generates a no-argument constructor
@AllArgsConstructor // Lombok: Generates a constructor with all arguments
public class Transaction {

    @Id // Marks this field as the Primary Key
    @GeneratedValue(strategy = GenerationType.IDENTITY) // Configures the ID to be auto-generated by the database
    private Long id;

    private String accountId;

    private BigDecimal amount;

    private String type;
}